pref = ""
table_query = [
    {
        "entidad": "tipos",
        "query": [],
        "params": ["_p1"],
        "def": [""],
       "query02": "CALL spTipos('_p1')",
    },
    {
        "entidad": "usuarios",
        "query": [],
        "head": ["","ID","NOMBRE", "TELEFONO", "CORREO","ESTADO", "CARGO ID", "CARGO"],
        "params": ["_p1", "_p2", "_p3","_id"],
        "def": ["", "0", "", "0"],
       "query01": "CALL spUsuarios(1, '_p1', _p2,'', _id, 100)",
       "query02": "CALL spUsuarios(2, '', 0,'', 0, 0)",
       "query03": "CALL spUsuarios(3, \"_p1\", 0, '', 0, 0)",
       "query04": "CALL spUsuarios(4,\"_p1\", _p2, \"_p3\", 0, 0)",
       "query05": "CALL spUsuarios(5, '_p1', 0, '', 0, 0)",
       "query06": "CALL spUsuarios(6, '_p1', 0, '_p3', 0,0)",
       "query07": "CALL spUsuarios(7, '_p1', 0, '', 0, 0)",
       "query08": "CALL spUsuarios(7, '', 0, '', _id, 0)"
    },
    {
        "entidad": "cargos",
        "query": [],
        "head": ["","ID", "CARGO"],
        "params": ["_p1", "_p2",'_id'],
        "def": ["", "0","0"],
       "query01": "CALL spCargos(1, '_p1', _p2,_id, 0)",
       "query02": "CALL spCargos(2, '', 0, 0, 0)",
       "query03": "CALL spCargos(3, \"_p1\", 0, 0, 0)",
       "query04": "CALL spCargos(4,\"_p1\", _p2, 0, 0)",
       "query05": "CALL spCargos(5, '_p1', 0, 0, 0)",
    },
    {
        "entidad": "funcionalidades",
        "query": [],
        "head": ["","ID", "FUNCIONALIDAD"],
        "params": ["_p1", "_p2",'_id'],
        "def": ["", "0","0"],
       "query01": "CALL spFuncionalidades(1, '_p1', _p2,_id, 0)",
       "query02": "CALL spFuncionalidades(2, '', 0, 0, 0)",
       "query03": "CALL spFuncionalidades(3, \"_p1\", 0, 0, 0)",
       "query04": "CALL spFuncionalidades(4,\"_p1\", _p2, 0, 0)",
       "query05": "CALL spFuncionalidades(5, '_p1', 0, 0, 0)",
    },

    {
        "entidad": "perfiles",
        "query": [],
        "head": ["", "CARGO_ID", "CARGO", "FUNCIONALIDAD_ID", "FUNCIONALIDAD","PERMISO"],
        "params": ["_p1", "_p2", "_p3", '_pkToDelete', '_id'],
        "def":["", "0", "0", "", "0"],
        #(IN `_query` INT, IN `_p1` VARCHAR(250), IN `_p2` INT, IN `_p3` INT, IN `_pairsToDelete` JSON, IN `_id` INT, IN `_limit` INT)
        "query01": "CALL spPerfiles(1, '', '_p2', '_p3', '\"\"', _id, 100)",
        "query03": "CALL spPerfiles(3, '_p1', 0, 0, '\"\"', 0, 0)",
        "query04": "CALL spPerfiles(4, '_p1', _p2, _p3, '\"\"', 0, 0)",
        "query05": "CALL spPerfiles(5, '', 0, 0, '_pkToDelete', 0, 0)",
    },
    {
        "entidad": "proveedores",
        "query": [],
        "head": ["", "ID", "RUT", "NOMBRE", "DIRECCION", "TELEFONO", "CORREO", "SITIO WEB"],
        "params": ["_p1", "_p2", "_p3","_id"],
        "def": ["", "0", "", "0"],
       "query01": "CALL spProveedores(1, '_p1', 0, '_p3', _id, 0)",
       "query02": "CALL spProveedores(2, '', 0,'', 0, 0)",
       "query03": "CALL spProveedores(3, \"_p1\", 0, '', 0, 0)",
       "query04": "CALL spProveedores(4,\"_p1\", _p2, '', 0, 0)",
       "query05": "CALL spProveedores(5, '_p1', 0, '', 0, 0)",
    },
    {
        "entidad": "cristales",
        "query": [],
        "head": ["", "ID", "RUT", "NOMBRE", "DIRECCION", "TELEFONO", "CORREO", "SITIO WEB"],
        "params": ["_p1", "_p2", "_pMarca","_pProveedor","_pDiseño", "_pIndice","_pMaterial", "_´pColor", "_pTratamiento", "_pEsp","_pCil","_pDiametro", "_id"],
        "def": ["", "0", "", "0"],
       "query01": "CALL spCristales(1, '', '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);",
       "query02": "CALL spProveedores(2, '', 0,'', 0, 0)",
       "query03": "CALL spProveedores(3, \"_p1\", 0, '', 0, 0)",
       "query04": "CALL spProveedores(4,\"_p1\", _p2, '', 0, 0)",
       "query05": "CALL spProveedores(5, '_p1', 0, '', 0, 0)",
    },
    
]